<?php

/**
 * @file
 * Example of integration with Views..
 */

/**
 * Implements hook_views_data().
 */
function fruity_views_views_data() {
  $views_data = [];

  $views_data['fruit']['table'] = [
    'group' => t('Tables can be grouped together for UX convenience. This label is actually visible in the Views UI.'),
    // This is a base table, so we declare it to Views.
    'base' => [
      // The primary key of this table. Views utilizes it for various internal
      // tasks. In fact, Views module requires all base tables to have a single-
      // column primary key.
      'field' => 'id',
      'title' => t('Human-friendly name of this base table. This label is actually visible in the Views UI.'),
      'help' => t('A little more verbose description of this table, also visible in the views UI.'),
    ],
  ];

  // As we describe the Views field 'label' that belongs to 'fruit' table, we
  // nest it respectively within $views_data array.
  $views_data['fruit']['label'] = [
    // Human friendly name of your Views field.
    'title' => t('Fruit label'),
    // A little more verbose description of your Views field.
    'help' => t('Name of the fruit.'),
    // Apart from field we could also describe sorting, filtering on this
    // column, but for now let's just stick to the 'field' part.
    'field' => [
      // In the 'id' key we place the name of Views field plugin that is
      // responsible for operating our 'label' column. The id "standard"
      // corresponds to \Drupal\views\Plugin\views\field\Standard class. It is
      // an extremely simplistic straightforward field plugin that appends the
      // column into SELECT query (see ::query() method) and then displays the
      // fetched column as field output (see ::render() method).
      'id' => 'standard',
    ],
    // So let's tell Views sorting by this column is actually possible.
    'sort' => [
      // The id "standard" corresponds to
      // \Drupal\views\Plugin\views\sort\Standard class. It is a dead straight
      // forward implementation of sorting that blindly sorts like:
      // "ORDER BY [column name] [sort direction, i.e. ASC/DESC]". This is just
      // good enough given we want to sort by fruit label alphabetically.
      'id' => 'standard',
    ],
    // By declaring 'filter' key we communicate to Views that this column can be
    // filtered on.
    'filter' => [
      // The id "string" corresponds to
      // \Drupal\views\Plugin\views\filter\StringFilter which according to its
      // documentation is a reasonable filter for columns that contain strings.
      'id' => 'string',
    ],
    // The key 'argument' denotes how Views could use contextual filters on the
    // column in question.
    'argument' => [
      // Because the label column is just a simple string, we are using the
      // "string" argument handler which corresponds to
      // \Drupal\views\Plugin\views\argument\StringArgument class.
      'id' => 'string',
    ],
  ];

  $views_data['fruit']['weight'] = [
    'title' => t('Fruit weight'),
    'help' => t('Weight of the fruit casted to kilograms.'),
    'field' => [
      // Note that now in the 'id' key we are using ID of the Views field plugin
      // we have just coded.
      'id' => 'fruit_weight',
      // As our custom 'fruit_weight' plugin requires additional definition,
      // let's properly supply to it name of the column that holds units of
      // weight.
      'additional fields' => [
        'units' => 'weight_unit',
      ],
    ],
    'sort' => [
      // Observe that we tell Views to use our custom sort handler for sorting
      // by this column.
      'id' => 'fruit_weight',
      // As our sort handler expects 2 additional definition items, let us
      // provide them correspondingly.
      'unit_column' => 'weight_unit',
      'lb_to_kg' => 0.4535924,
    ],
    // The below key specifies to Views that it is also possible to filter by
    // this column and in order to do filtering, it should use the
    // 'fruit_weight' filter handler. As we have agreed, this filter handler
    // expects only 1 definition item - name of the column where weight units
    // are stored.
    'filter' => [
      'id' => 'fruit_weight',
      'unit_column' => 'weight_unit',
    ],
    // This is where we tell Views that for contextual filters on 'weight', we
    // want to use 'fruit_weight' argument handler.
    'argument' => [
      'id' => 'fruit_weight',
      // As 'fruit_weight' argument handler expects 'unit_column' definition
      // item we kindly provide it to the handler.
      'unit_column' => 'weight_unit',
    ],
  ];

  $views_data['fruit_relations']['table'] = [
    'title' => t('Related fruit'),
    'group' => t('We would probably want to place this table into the same group as its base table for consistency in the UI.'),
    // Watch out! This is not a base table, so we use a different key and
    // explain to Views how this table can be JOINed to our base table of
    // 'fruit'.
    'join' => [
      // We are explaining Views how 'fruit_relations' can be JOINed to 'fruit'.
      // By the way, you do not necessarily have to JOIN onto a base table. You
      // may as well JOIN in chain a few non-base tables. Although for a table
      // to become visible in Views UI, it must be connected one way or another
      // to a base table on which the view is being built.
      'fruit' => [
        // Column from 'fruit' table which will participate in the JOIN clause.
        'left_field' => 'id',
        // Column from 'fruit_relations' table that will participate in the JOIN
        // clause.
        'field' => 'fruit_id',
      ],
    ],
  ];

  return $views_data;
}
